[platformio]
default_envs = esp32c6_arduino

[env]
platform = espressif32
monitor_speed = 115200

; IMPORTANT:
; Set this to the correct PlatformIO board ID for your ESP32-C6 dev kit.
; Example IDs vary by PlatformIO version.
board = esp32-c6-devkitm-1

[env:esp32c6_arduino]
framework = arduino

[env:esp32c6_espidf]
framework = espidf